# Task 1.2 – Modeling and Tuning (ECG Classification)

Read training-data (ECG-time series) as pickle from task 1

In [1]:
import pickle
from collections import Counter

# Load the dataset from task 1
with open("../data/split_data.pkl", "rb") as f:
    X_train_split, X_val_split, y_train_split, y_val_split = pickle.load(f)

# X_train_split: Trainingsdaten
# X_val_split: Validierungsdaten
# y_train_split: Labels für Trainingsdaten
# y_val_split: Labels für Validierungsdaten

print(f"Trainingsdaten: {len(X_train_split)} Zeitreihen")
print(f"Validierungsmenge: {len(X_val_split)} Beispiele")

# class distribution
print("Train-class-distribution:", Counter(y_train_split))
print("Val-class-distribution:", Counter(y_val_split))


Trainingsdaten: 4943 Zeitreihen
Validierungsmenge: 1236 Beispiele
Train-class-distribution: Counter({0: 2910, 2: 1412, 1: 439, 3: 182})
Val-class-distribution: Counter({0: 728, 2: 353, 1: 110, 3: 45})


Padding of all training time series (= adding 0 to the ECG-time series to make them evenly long) 
evenly sized

In [2]:
import numpy as np

def pad_sequences(sequences, max_len=None):
    if not max_len:
        max_len = max(len(seq) for seq in sequences)
    return np.array([np.pad(seq, (0, max_len - len(seq))) for seq in sequences])

# Check the maximum length of training and validation sequences
max_len = max(max(len(seq) for seq in X_train_split),
              max(len(seq) for seq in X_val_split))

print("Maximum length of training and validation sequences:", max_len)

# Pad the sequences to the same length
X_train_split = pad_sequences(X_train_split, max_len)
X_val_split = pad_sequences(X_val_split, max_len)

# Check the shape of the padded sequences
print("Shape of padded training data:", X_train_split.shape)
print("Shape of padded validation data:", X_val_split.shape)

Maximum length of training and validation sequences: 18286
Shape of padded training data: (4943, 18286)
Shape of padded validation data: (1236, 18286)


Convert 1D-NumPy-Arrays into 2D-Tensor with short-time Fourier transform (STFT)

In [3]:
import torch

def apply_stft_numpy(X, n_fft=256, hop_length=128):
    """
    Wandelt ein NumPy-Array mit gepaddeten Zeitreihen in STFT-Spektren um.
    
    Args:
        data_np (np.ndarray): Input (n_samples, sequence_length)
        n_fft (int): Größe des STFT-Fensters
        hop_length (int): Schrittweite der Fenster
    
    Returns:
        torch.Tensor: STFT-Magnitude-Spektren (n_samples, freq_bins, time_steps)
    """
    # convert to torch tensor
    data_tensor = torch.tensor(X, dtype=torch.float32)

    # window function for STFT
    window = torch.hann_window(n_fft)

    # empty list to store STFT results
    stft_results = []

    # iterate over each time series
    for i in range(data_tensor.shape[0]):
        # compute STFT
        stft = torch.stft(
            data_tensor[i], 
            n_fft=n_fft, 
            hop_length=hop_length, 
            window=window, 
            return_complex=True
            )
        
        # compute magnitude
        stft_magnitude = torch.abs(stft)
        
        # append to results
        stft_results.append(stft_magnitude)

        # convert into 3D tensor
        stft_tensor = torch.stack(stft_results)
        
    return stft_tensor
    
# Apply STFT to the training and validation data
X_train_stft = apply_stft_numpy(X_train_split)  # Output: Tensor mit Shape (4943, freq_bins, time_steps)
X_val_stft = apply_stft_numpy(X_val_split)

# Check the shape of the STFT results
print("Shape of STFT training data:", X_train_stft.shape)
print("Shape of STFT validation data:", X_val_stft.shape)

Shape of STFT training data: torch.Size([4943, 129, 143])
Shape of STFT validation data: torch.Size([1236, 129, 143])


Convert tensors into DataLoader objects for the model training

In [8]:
from torch.utils.data import Dataset, DataLoader

# Create a custom Dataset class for the STFT data
class ECGSpectrogramDataset(Dataset):
    def __init__(self, X, y):
        self.X = X.unsqueeze(1)  # füge Channel-Dimension hinzu → (N, 1, Freq, Time)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

# function to create DataLoader objects for training and validation
def create_spectrogram_dataloaders(X_train_stft, y_train, X_val_stft, y_val, batch_size=32):
    """
    Erstellt trainierbare DataLoader aus STFT-Tensoren und Label-Listen.

    Args:
        X_train_stft (torch.Tensor): Trainingsdaten (N_train, Freq, Time)
        y_train (List[int]): Trainingslabels
        X_val_stft (torch.Tensor): Validierungsdaten (N_val, Freq, Time)
        y_val (List[int]): Validierungslabels
        batch_size (int): Größe der Batches

    Returns:
        train_loader, val_loader: DataLoader-Objekte
    """
    train_dataset = ECGSpectrogramDataset(X_train_stft, y_train)
    val_dataset = ECGSpectrogramDataset(X_val_stft, y_val)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, val_loader

# Create DataLoader objects for training and validation
train_loader, val_loader = create_spectrogram_dataloaders(
    X_train_stft, y_train_split, X_val_stft, y_val_split
)

# Check the shape of a batch from the DataLoader and the labels
X_batch, y_batch = next(iter(train_loader))
print("Batch shape (X):", X_batch.shape)
print("Batch shape (y):", y_batch.shape)
#print("Labels im Batch:", X_batch.tolist())
#print("Labels im Batch:", y_batch.tolist())


Batch shape (X): torch.Size([32, 1, 129, 143])
Batch shape (y): torch.Size([32])


Definition and training of CNN-model (Convolutional Neural Network)

In [10]:
import torch.nn as nn

# Define the CNN model for ECG classification
# The model architecture is a simple CNN with two convolutional layers followed by two fully connected layers.
class ECGCNN(nn.Module):
    def __init__(self, num_classes=4):
        super(ECGCNN, self).__init__()
        self.conv_block = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d((2, 2)),
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d((2, 2)),
        )
        self.flatten = nn.Flatten()
        self.fc = nn.Sequential(
           nn.Linear(35840, 64),  # anpassen je nach STFT-Größe!!! check shape once
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        x = self.conv_block(x)
        # print(x.shape) # only once for testing the model architecture
        x = self.flatten(x)
        x = self.fc(x)
        return x

# # method to train the model 
# def train_model(model, train_loader, val_loader, epochs=10, lr=0.001):
    
#     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#     model.to(device)

#     criterion = nn.CrossEntropyLoss()
#     optimizer = torch.optim.Adam(model.parameters(), lr=lr)

#     for epoch in range(epochs):
#         model.train()
#         train_loss, correct, total = 0.0, 0, 0

#         for X_batch, y_batch in train_loader:
#             X_batch, y_batch = X_batch.to(device), y_batch.to(device)
#             optimizer.zero_grad()
#             outputs = model(X_batch)
#             loss = criterion(outputs, y_batch)
#             loss.backward()
#             optimizer.step()

#             train_loss += loss.item()
#             _, predicted = torch.max(outputs, 1)
#             total += y_batch.size(0)
#             correct += (predicted == y_batch).sum().item()

#         train_acc = correct / total

#         # evaluate on validation set
#         model.eval()
#         val_loss, val_correct, val_total = 0.0, 0, 0
#         with torch.no_grad():
#             for X_val, y_val in val_loader:
#                 X_val, y_val = X_val.to(device), y_val.to(device)
#                 outputs = model(X_val)
#                 loss = criterion(outputs, y_val)
#                 val_loss += loss.item()
#                 _, predicted = torch.max(outputs, 1)
#                 val_total += y_val.size(0)
#                 val_correct += (predicted == y_val).sum().item()

#         val_acc = val_correct / val_total

#         # print the training and validation loss and accuracy
#         print(f"Epoch {epoch+1}: "
#               f"Train Loss={train_loss:.4f}, Train Acc={train_acc:.4f}, "
#               f"Val Loss={val_loss:.4f}, Val Acc={val_acc:.4f}")


# # only once for testing the model architecture
# # X_batch, _ = next(iter(train_loader))
# # cnn_model = ECGCNN()
# # cnn_model(X_batch)  # ruft automatisch forward() auf

# # instantiate the model and train it   
# cnn_model = ECGCNN()

# # train the model
# train_model(cnn_model, train_loader, val_loader, epochs=10)

# # # Modell speichern
# # torch.save(cnn_model.state_dict(), "../models/cnn_model_wt_tune.pth")

# # load the model
# # cnn_model.load_state_dict(torch.load("model.pth"))

# # delete the model to free up memory
# # del cnn_model

# # Check the number of parameters in the model
# print("Anzahl der Modell-Parameter:", sum(p.numel() for p in cnn_model.parameters()))

Tuning

In [ ]:
import torch.optim as optim
from itertools import product
import pandas as pd


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Trainings- & Evaluationsfunktion
def train_and_eval(model, train_loader, val_loader, lr, weight_decay, optimizer_type, epochs=10):
    criterion = nn.CrossEntropyLoss()
    if optimizer_type == "adam":
        optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    elif optimizer_type == "sgd":
        optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9, weight_decay=weight_decay)
    else:
        raise ValueError("Unsupported optimizer")

    model.to(device)
    best_acc = 0
    val_loss_final = 0.0

    for epoch in range(epochs):
        model.train()
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            loss.backward()
            optimizer.step()

        # Evaluation
        model.eval()
        val_correct, val_total, val_loss = 0, 0, 0.0
        with torch.no_grad():
            for X_val, y_val in val_loader:
                X_val, y_val = X_val.to(device), y_val.to(device)
                outputs = model(X_val)
                loss = criterion(outputs, y_val)
                val_loss += loss.item()
                _, predicted = torch.max(outputs, 1)
                val_total += y_val.size(0)
                val_correct += (predicted == y_val).sum().item()

        val_acc = val_correct / val_total
        val_loss_final = val_loss / len(val_loader)

        if val_acc > best_acc:
            best_acc = val_acc
            filename = f"best_lr{lr}_opt{optimizer_type}.pth"
            torch.save(model.state_dict(), f"../models/{filename}")

    return best_acc, val_loss_final

# Hyperparameter-Raster
param_grid = {
    'lr': [0.001, 0.0005],
    'weight_decay': [0.0, 1e-4],
    'optimizer_type': ['adam', 'sgd'],
    'epochs': [10]
}

results = []

# Tuning Loop
for params in product(*param_grid.values()):
    param_dict = dict(zip(param_grid.keys(), params))
    print(f"\nTrainiere mit Parametern: {param_dict}")

    model = ECGCNN()

    val_acc, val_loss = train_and_eval(model, train_loader, val_loader, **param_dict)

    param_dict["val_accuracy"] = val_acc
    param_dict["val_loss"] = val_loss
    results.append(param_dict)

    del model
    torch.cuda.empty_cache()

# Ergebnisse speichern
df = pd.DataFrame(results)
df.to_csv("tuning_results.csv", index=False)
print("\nTuning abgeschlossen. Beste Ergebnisse gespeichert.")


Trainiere mit Parametern: {'lr': 0.001, 'weight_decay': 0.0, 'optimizer_type': 'adam', 'epochs': 10}

Trainiere mit Parametern: {'lr': 0.001, 'weight_decay': 0.0, 'optimizer_type': 'sgd', 'epochs': 10}

Trainiere mit Parametern: {'lr': 0.001, 'weight_decay': 0.0001, 'optimizer_type': 'adam', 'epochs': 10}

Trainiere mit Parametern: {'lr': 0.001, 'weight_decay': 0.0001, 'optimizer_type': 'sgd', 'epochs': 10}

Trainiere mit Parametern: {'lr': 0.0005, 'weight_decay': 0.0, 'optimizer_type': 'adam', 'epochs': 10}

Trainiere mit Parametern: {'lr': 0.0005, 'weight_decay': 0.0, 'optimizer_type': 'sgd', 'epochs': 10}

Trainiere mit Parametern: {'lr': 0.0005, 'weight_decay': 0.0001, 'optimizer_type': 'adam', 'epochs': 10}

Trainiere mit Parametern: {'lr': 0.0005, 'weight_decay': 0.0001, 'optimizer_type': 'sgd', 'epochs': 10}

✅ Tuning abgeschlossen. Beste Ergebnisse gespeichert.


In [25]:
from sklearn.metrics import classification_report, confusion_matrix, balanced_accuracy_score

# loop through the model files
for filename in ["best_lr0.001_optadam.pth", "best_lr0.001_optsgd.pth", "best_lr0.0005_optadam.pth", "best_lr0.0005_optsgd.pth", "cnn_model_wo_tune.pth"]:

    # Nach dem Training – Inference auf Validation
    all_preds = []
    all_labels = []

    # instantiate the model
    model = ECGCNN()

    # load the model from path
    model.load_state_dict(torch.load(f"../models/{filename}"))

    model.eval()
    with torch.no_grad():
        for X_val, y_val in val_loader:
            X_val = X_val.to(device)
            outputs = model(X_val)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(y_val.numpy())

    # print the model name
    print(f"\nModel: {filename}")

    # Klassifikationsbericht
    print(classification_report(all_labels, all_preds, digits=4))

    # Confusion Matrix
    print("Confusion Matrix:\n", confusion_matrix(all_labels, all_preds))

    # Balanced Accuracy
    print("Balanced Accuracy:", balanced_accuracy_score(all_labels, all_preds))

    # delete the model to free up memory
    del model


Model: best_lr0.001_optadam.pth
              precision    recall  f1-score   support

           0     0.7063    0.8654    0.7778       728
           1     0.3600    0.1636    0.2250       110
           2     0.5000    0.3909    0.4388       353
           3     0.3333    0.1333    0.1905        45

    accuracy                         0.6408      1236
   macro avg     0.4749    0.3883    0.4080      1236
weighted avg     0.6030    0.6408    0.6104      1236

Confusion Matrix:
 [[630  13  79   6]
 [ 42  18  49   1]
 [195  15 138   5]
 [ 25   4  10   6]]
Balanced Accuracy: 0.3883222891367367

Model: best_lr0.001_optsgd.pth
              precision    recall  f1-score   support

           0     0.5890    1.0000    0.7413       728
           1     0.0000    0.0000    0.0000       110
           2     0.0000    0.0000    0.0000       353
           3     0.0000    0.0000    0.0000        45

    accuracy                         0.5890      1236
   macro avg     0.1472    0.2500    0.1

c:\Users\Analyst32\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Analyst32\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Analyst32\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf


Model: best_lr0.0005_optadam.pth
              precision    recall  f1-score   support

           0     0.6552    0.8379    0.7354       728
           1     0.3846    0.1364    0.2013       110
           2     0.4417    0.3003    0.3575       353
           3     0.2692    0.1556    0.1972        45

    accuracy                         0.5971      1236
   macro avg     0.4377    0.3575    0.3729      1236
weighted avg     0.5561    0.5971    0.5603      1236

Confusion Matrix:
 [[610  10  92  16]
 [ 61  15  34   0]
 [234  10 106   3]
 [ 26   4   8   7]]
Balanced Accuracy: 0.357528641487565

Model: best_lr0.0005_optsgd.pth
              precision    recall  f1-score   support

           0     0.5890    1.0000    0.7413       728
           1     0.0000    0.0000    0.0000       110
           2     0.0000    0.0000    0.0000       353
           3     0.0000    0.0000    0.0000        45

    accuracy                         0.5890      1236
   macro avg     0.1472    0.2500    0.

c:\Users\Analyst32\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Analyst32\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Analyst32\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf


Model: cnn_model_wo_tune.pth
              precision    recall  f1-score   support

           0     0.6070    0.9354    0.7362       728
           1     0.2632    0.0455    0.0775       110
           2     0.4301    0.1133    0.1794       353
           3     0.5000    0.0222    0.0426        45

    accuracy                         0.5882      1236
   macro avg     0.4501    0.2791    0.2589      1236
weighted avg     0.5220    0.5882    0.4933      1236

Confusion Matrix:
 [[681   8  38   1]
 [ 95   5  10   0]
 [308   5  40   0]
 [ 38   1   5   1]]
Balanced Accuracy: 0.279107693927099
